### ISSUE TITLE
Saving image loses c2pa information

### ISSUE THREAD

**Issue by shayan-NECX** [contentauth/c2pa-python-example#10]
Hi, thanks for the work. I am trying to save image with c2pa information in app.py code, it does save the image but then when i read c2pa information, it says there is no manifest attached. 

However, when i follow the tutorial, as is, and do the curl request, then the output image saved by it, has the c2pa information. 

I dont understand why would this happen? Why saving image after receiving image bytes, loses the c2pa content ? Please guide.
```

@app.route("/attach", methods=["POST"])
def resize():
    request_data = request.get_data()

    manifest = json.dumps({
        "title": "image2.jpg",
        "format": "image/jpeg",
        "claim_generator_info": [
            {
                "name": "c2pa test",
                "version": "0.0.1"
            }
        ],
        "assertions": [
            {
                "label": "c2pa.actions",
                "data": {
                    "actions": [
                        {
                            "action": "c2pa.edited",
                            "softwareAgent": {
                                "name": "C2PA Python Example",
                                "version": "0.1.0"
                            }
                        }
                    ]
                }
            }
        ]
    })

    builder = Builder(manifest)

    signer = create_signer(sign, SigningAlg.ES256,
                           cert_chain, "http://timestamp.digicert.com")

    result = io.BytesIO(b"")
    builder.sign(signer, "image/jpeg", io.BytesIO(request_data), result)

    with open('result.txt','w') as f:
        print(result.getvalue(),file=f)

    image = Image.open(result)

    # Save the image IO object to a file
    image.save('output_image5.jpg')
    
    image = Image.open(io.BytesIO(result.getvalue()))

    # # Save the image bytes to a file
    image.save('output_image6.jpg')
    with open('byte_result.txt','w') as f:
        print(result.getvalue(),file=f)

    print("End")
    return result.getvalue()
```

**Comment by ttbuffey** [comment]
@shayan-NECX it seems you run the api successful at the first place.  however i get some issue that I need your help to confirm where is wrong ehen i follow the guide. I can't even run the curl successfully.

i also get someissues, after run the curl command I get an error when run api.py 
`**builder.sign(signer, "image/jpeg", io.BytesIO(request_data), result)**
  File "/Users/i302707/Documents/pii/c2pa-python-example/ven_3.10.5/lib/python3.10/site-packages/c2pa/c2pa_api/c2pa_api.py", line 129, in sign
    return super().sign(signer, format, C2paStream(input), C2paStream(output))
  File "/Users/i302707/Documents/pii/c2pa-python-example/ven_3.10.5/lib/python3.10/site-packages/c2pa/c2pa/c2pa.py", line 925, in sign
    rust_call_with_error(
  File "/Users/i302707/Documents/pii/c2pa-python-example/ven_3.10.5/lib/python3.10/site-packages/c2pa/c2pa/c2pa.py", line 283, in rust_call_with_error
    uniffi_check_call_status(error_ffi_converter, call_status)
  File "/Users/i302707/Documents/pii/c2pa-python-example/ven_3.10.5/lib/python3.10/site-packages/c2pa/c2pa/c2pa.py", line 313, in uniffi_check_call_status
    raise error_ffi_converter.lift(call_status.error_buf)
**c2pa.c2pa.c2pa.Error.Signature: reason='COSE error parsing certificate`**

1. what i have done is first run

`python setup.py create-key-and-csr 'CN=John Smith,O=C2PA Python Demo'`
 kms-signing.csr file is cgenerated

2. then create fake rootCA

`openssl req -x509 \
-days 1825 \
-newkey rsa:2048 \
-keyout rootCA.key \
-out rootCA.crt`

3. then sign the CSR created in step 1 with the temporary test CA key
 `openssl x509 -req \
-CA rootCA.crt \
-CAkey rootCA.key \
-in kms-signing.csr \
-out kms-signing.crt \
-days 365 \
-copy_extensions copyall`

4. then create chain.pem
`cat kms-signing.crt rootCA.crt > chain.pem` 

5. FLASK_KMS_KEY_ID="$KMS_KEY_ID" FLASK_CERT_CHAIN_PATH="./chain.pem" flask run
6. curl command, i get the "COSE error parsing certificate" error from the builder.sign

**Comment by shayan-NECX** [comment]
Never mind, i was able to create image bytes, send as image byte string and retain C2PA information in images too. I will close the issue.

Regards,
Shayan

________________________________
